export const categories = [
  "desmamante macho",
  "desmamante hembra",
  "vaquilla",
  "toreton",
  "novillo",
  "vaquilla preñada",
  "terminado",
  "toro reproductor",
  "vaca seca",
  "vaca gorda",
  "reproductor",
  "maíz",
  "burlanda de maíz",
  "vaca de descarte",
  "vaca preñada",
  "vaca con cria",
  "sorgo grano",
  "toro",
] as const;
